- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Allow SSH through UFW
  ufw:
    rule: allow
    port: 22
  when: ansible_distribution == "Ubuntu"

- name: Enable UFW and set default deny policy
  ufw:
    state: enabled
    policy: deny
  when: ansible_distribution == "Ubuntu"
