- hosts: all
  become: true
  vars_files:
    - config.yml

  tasks:
    - name: Run roles assigned to this host
      include_role:
        name: "{{ item }}"
      loop: "{{ node_roles[inventory_hostname] }}"
