- name: Join as control-plane
  shell: |
    kubeadm join {{ k8s_control_plane_ip }}:{{ k8s_control_plane_port }} \
      --token {{ k8s_token }} \
      --discovery-token-ca-cert-hash {{ k8s_discovery_hash }} \
      --control-plane \
      --certificate-key {{ k8s_certificate_key }}
  args:
    creates: /etc/kubernetes/admin.conf
  when: inventory_hostname in groups['k8s_control_plane'] and inventory_hostname != groups['k8s_control_plane'][0]

- name: Join as worker
  shell: |
    kubeadm join {{ k8s_control_plane_ip }}:{{ k8s_control_plane_port }} \
      --token {{ k8s_token }} \
      --discovery-token-ca-cert-hash {{ k8s_discovery_hash }}
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: inventory_hostname in groups['k8s_workers']
