- name: Install prerequisites & container runtime
  import_tasks: install.yml

- name: Initialize control plane on primary
  import_tasks: init_cluster.yml
  when: inventory_hostname == k8s_control_planes[0]

- name: Join as additional control-plane
  import_tasks: join_cluster.yml
  when:
    - inventory_hostname in k8s_control_planes
    - inventory_hostname != k8s_control_planes[0]

- name: Join as worker
  import_tasks: join_cluster.yml
  when: inventory_hostname not in k8s_control_planes
